NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [5]:
a.dtype.name

'int64'

In [6]:
a.ndim

2

In [7]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

Array Creation

In [10]:
b = np.array([2,3,4,5])
print b

[2 3 4 5]


In [13]:
c = np.array([([2,3,4]),([1,2,3])])
print c

[[2 3 4]
 [1 2 3]]


In [15]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2,3))

array([[  1.72723371e-077,   1.72723371e-077,   2.26035163e-314],
       [  2.26022947e-314,   2.26039992e-314,   2.26020490e-314]])

Scalar 0 Dimension

Vector 1 Dimension 1*n

Matrics 2 Dimension m*n

Tensor N dimension collection values 


In [4]:
#Scalar

s = np.array(3)
print s
print s.shape

3
()


In [5]:
#Vector

v = np.array([1,2,3])
print v
print v.shape

[1 2 3]
(3,)


In [6]:
print v[1]
print v[0:]

2
[1 2 3]


In [8]:
#Matrices

m = np.array([[1,2,3],[4,5,6],[5,6,7]])
print m
print m.shape

[[1 2 3]
 [4 5 6]
 [5 6 7]]
(3, 3)


In [9]:
#Tensor
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print t
print t.shape

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]
(3, 3, 2, 1)


In [10]:
#Changing shape

x = v.reshape([1,3])
print x



[[1 2 3]]


In [12]:
x = v.reshape([3,1])
print x

[[1]
 [2]
 [3]]


ELEMENT WISE MATRIX OPERATIONS

In [17]:
# without numpy
values = [1,2,3,4,5]

for i in range(len(values)):
    values[i]=values[i]+5

print values
    

[6, 7, 8, 9, 10]


In [19]:
values = [1,2,3,4,5]
np.array(values)+5

array([ 6,  7,  8,  9, 10])

In [21]:
x = np.multiply(values,5)
print x

[ 5 10 15 20 25]


In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[2,1]])

print a

print b

[[1 2]
 [3 4]]
[[2 3]
 [2 1]]


In [25]:
a + b

array([[3, 5],
       [5, 5]])

In [26]:
a.shape

(2, 2)

MATRIX MULTIPLICATION

element wise multiplications m*n

matrix product using function matmul

dot product and matmul yields the same dimensions while working on 2 dimensional data


In [31]:
m = np.array([[1,2,3],[3,4,5]])
n = np.array([[2,3,4],[2,2,2],[1,2,3]])

print m.shape
print n.shape
o = np.matmul(m,n)
print o
print o.shape

(2, 3)
(3, 3)
[[ 9 13 17]
 [19 27 35]]
(2, 3)


Matrix transpose

In [33]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print m 

print m.T

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [37]:
s = np.array([1,2,3,4])

print s

s.reshape(2,2)

[1 2 3 4]


array([[1, 2],
       [3, 4]])